language: rust
rust:
  - nightly
sudo: required
install:
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl2-dev
notifications:
  slack: redox-os:t5jWurX9sFfgurPznqdECoKN
  email: false
