[package]
name = "orbtk"
description = "The Orbital Widget Toolkit"
repository = "https://github.com/redox-os/orbtk"
version = "0.2.20"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[lib]
name = "orbtk"
path = "src/lib.rs"

[dependencies]
orbclient = "0.3"
orbfont = "0.1"
orbimage = "0.1"

