[package]
name = "orbtk"
version = "0.3.1-alpha-1"
authors = [
    "Florian Blasius <flovanpt@posteo.de>",
    "Jeremy Soller <jackpot51@gmail.com>"
]
description = "The Orbital Widget Toolkit"
documentation = "https://docs.rs/orbtk"
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = [
    "orbital",
    "redox",
    "ui",
]
edition = "2018"

[lib]
name = "orbtk"
path = "src/lib.rs"

[profile.dev]
opt-level = 1

[dependencies]
orbtk-utils = "0.3.0-alpha1"
orbtk-tree = "0.3.0-alpha1"
orbtk-proc-macros = "0.3.0-alpha1"
orbtk-api = "0.3.0-alpha1"
orbtk-css-engine = "0.3.0-alpha1"
orbtk-render = "0.3.0-alpha1"
orbtk-shell = "0.3.0-alpha1"
orbtk-theme = "0.3.0-alpha1"
orbtk-widgets = "0.3.0-alpha1"
dces = "0.2"

[dev-dependencies]
euc = "0.4.2"
vek = "0.9.10"

[features]
debug = ["orbtk-api/debug"]
 
[workspace]
members = [
    "crates/utils",
    "crates/tree",
    "crates/proc-macros",
    "crates/api",
    "crates/css-engine", 
    "crates/render",
    "crates/shell",
    "crates/theme",
    "crates/widgets",
]