[package]
name = "orbtk"
version = "0.3.0"
authors = ["OrbTk Focus Time Group, Redox OS Developers"]
description = "The Orbital Widget Toolkit"
documentation = "https://docs.rs/orbtk"
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = [
    "orbital",
    "redox",
    "ui",
]

[lib]
name = "orbtk"
path = "src/lib.rs"

[dependencies]
cssparser = "0.17.0"
lazy_static = "1.2.0"
dces = { git = "https://gitlab.com/orbtk/dces-rust.git" }
orbclient = "0.3.17"
orbfont = { git = "https://gitlab.redox-os.org/redox-os/orbfont.git" }
# orbfont = { path = "/Users/florian.blasius/Projects/Focus-Time/orbfont/" }
orbimage = "0.1.16"
