[[apps]]
name = "showcase"
width = 468
height = 730
assets = "assets/showcase/"
    [[apps.fonts]]
    font_family = "MaterialIcons-Regular"
    src = "crates/theme_default/assets/fonts/MaterialIcons.ttf"
    [[apps.fonts]]
    font_family = "Roboto-Regular"
    src = "crates/theme_default/assets/fonts/Roboto-Regular.ttf"
    [[apps.fonts]]
    font_family = "Roboto-Medium"
    src = "crates/theme_default/assets/fonts/Roboto-Medium.ttf"

[[apps]]
name = "calculator"
width = 212
height = 360

[[apps]]
name = "canvas"
width = 468
height = 730
    [[apps.fonts]]
    font_family = "MaterialIcons-Regular"
    src = "crates/theme_default/assets/fonts/MaterialIcons.ttf"
    [[apps.fonts]]
    font_family = "Roboto-Regular"
    src = "crates/theme_default/assets/fonts/Roboto-Regular.ttf"
    [[apps.fonts]]
    font_family = "Roboto-Medium"
    src = "crates/theme_default/assets/fonts/Roboto-Medium.ttf"
