[[apps]]
name = "widgets"
width = 468
height = 730
    [[apps.fonts]]
    font_family = "MaterialIcons-Regular"
    src = "crates/theme/src/fonts/MaterialIcons.ttf"
    [[apps.fonts]]
    font_family = "Roboto-Regular"
    src = "crates/theme/src/fonts/Roboto-Regular.ttf"
    [[apps.fonts]]
    font_family = "Roboto-Medium"
    src = "crates/theme/src/fonts/Roboto-Medium.ttf"

[[apps]]
name = "calculator"
width = 212
height = 360

[[apps]]
name = "image"
width = 800
height = 420
assets = "res/"

[[apps]]
name = "canvas"
width = 468
height = 730
    [[apps.fonts]]
    font_family = "MaterialIcons-Regular"
    src = "crates/theme/src/fonts/MaterialIcons.ttf"
    [[apps.fonts]]
    font_family = "Roboto-Regular"
    src = "crates/theme/src/fonts/Roboto-Regular.ttf"
    [[apps.fonts]]
    font_family = "Roboto-Medium"
    src = "crates/theme/src/fonts/Roboto-Medium.ttf"
