[package]
name = "orbtk-widgets"
version = "0.3.1-alpha3"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Base OrbTk widget library."
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["ui", "widgets"]
edition = "2018"

[dependencies]
dces = { git = "https://gitlab.redox-os.org/redox-os/dces-rust.git",  branch = "develop" }
orbtk-api = { path = "../api", version = "0.3.1-alpha3" }
orbtk-shell = { path = "../shell", version = "0.3.1-alpha3" }
orbtk-theme = { path = "../theme", version = "0.3.1-alpha3" }
orbtk-render = { path = "../render", version = "0.3.1-alpha3" }
orbtk-utils = { path = "../utils", version = "0.3.1-alpha3" }
orbtk-proc-macros = { version = "0.3.1-alpha3", path = "../proc-macros" }