[package]
name = "orbtk-render"
version = "0.1.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "2D Render library use by OrbTk."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["2D", "render", "canvas"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.20"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
raqote = { version = "0.7.3", default-features = false}
rusttype = "0.8.1"
image = "0.22.3"

[dependencies]
orbtk-utils = { version = "0.1.0", path = "../utils" }