[package]
name = "orbtk-shell"
version = "0.1.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Window shell crate used by OrbTk."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["shell", "window", "ui"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.19"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
spin_sleep = "0.3.7"
image = "0.22.3"

[target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "redox_os")))'.dependencies]
minifb = "0.13"

[target.'cfg(redox_os)'.dependencies]
minifb-fix = { git = "https://github.com/FloVanGH/rust_minifb", branch = "redox_unix" }

[dependencies]
orbtk-render = { version = "0.1.0", path = "../render" }
orbtk-utils = { version = "0.1.0", path = "../utils" }
lazy_static = "1.4.0"