[package]
name = "orbtk-shell"
version = "0.3.1-alpha3"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Window shell crate used by OrbTk."
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["shell", "window", "ui"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.20"
console_error_panic_hook = "0.1.6"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
spin_sleep = "0.3.7"
image = "0.23.4"

[target.'cfg(all(not(target_arch = "wasm32")))'.dependencies]
glutin = "0.24.0"
#minifb = "0.15"
# minifb = { git = "https://github.com/FloVanGH/rust_minifb", branch = "redox_unix" }

[dependencies]
orbtk-render = { path = "../render", version = "0.3.1-alpha3" }
orbtk-utils = { path = "../utils", version = "0.3.1-alpha3" }
lazy_static = "1.4.0"
raw-window-handle = "0.3.3"