[package]
name = "orbtk-shell"
version = "0.3.1-alpha4"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Window shell crate used by OrbTk."
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["shell", "window", "ui"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.20"
console_error_panic_hook = "0.1.6"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
spin_sleep = { version = "1.0", optional = true }
image = "0.23"
minifb = { git = "https://github.com/FloVanGH/rust_minifb", branch = "redox_unix", optional = true }
gl = { version = "0.14", optional = true }
glutin = { version = "0.24", optional = true }
euclid = { version = "0.20", optional = true }
font-kit = { version = "0.6", optional = true }
pathfinder_color = { version = "0.5", optional = true }
pathfinder_geometry = { version = "0.5.1", optional = true }
pathfinder_gl =  { version = "0.5", optional = true }
pathfinder_renderer =  { version = "0.5", optional = true }
pathfinder_resources =  { version = "0.5", optional = true }

[dependencies]
derive_more = "0.99"
orbtk-render = { path = "../render", version = "0.3.1-alpha4" }
orbtk-utils = { path = "../utils", version = "0.3.1-alpha4" }
lazy_static = "1.4.0"
raw-window-handle = "0.3.3"

[features]
default = ["spin_sleep", "minifb"]
pfinder = [
    "gl",
    "glutin",
    "euclid",
    "pathfinder_color",
    "pathfinder_geometry",
    "pathfinder_gl",
    "pathfinder_renderer",
    "pathfinder_resources",
    "font-kit"
]
log = []