[package]
name = "orbtk_widgets"
version = "0.4.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Integrated default OrbTk widget library with different themes."
edition = "2018"
keywords = ["gui", "ui", "ecs"]

[dependencies]
dces = { git = "https://gitlab.redox-os.org/redox-os/dces-rust.git",  branch = "develop" }