[package]
name = "orbtk-theme"
version = "0.1.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Default theme of OrbTk."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
license = "MIT"
keywords = ["css", "theme", "styling", "ui"]
edition = "2018"

[dependencies]
orbgl_api = { git = "https://gitlab.redox-os.org/redox-os/orbgl.git" }
orbtk-css-engine = { version = "0.1.0", path = "../css-engine" }
lazy_static = "1.3.0"