[package]
name = "orbtk-api"
version = "0.1.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "API crate that provides base api and elements for OrbTk like widgets basis."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
license = "MIT"
keywords = ["ui", "api"]
edition = "2018"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
orbclient = "0.3.22"

[dependencies]
dces = { git = "https://gitlab.redox-os.org/redox-os/dces-rust.git" }
orbtk-css-engine = { version = "0.1.0", path = "../css-engine" }
orbtk-render = { version = "0.1.0", path = "../render" }
orbtk-shell = { version = "0.1.0", path = "../shell" }
orbtk-utils = { version = "0.1.0", path = "../utils" }
orbtk-tree = { version = "0.1.0", path= "../tree" }
orbtk-theme = { version = "0.1.0", path= "../theme" }

[features]
experimental = []