[package]
name = "orbtk-api"
version = "0.3.0-alpha1"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "API crate that provides base api and elements for OrbTk like widgets basis."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["ui", "api"]
edition = "2018"

[dependencies]
dces = "0.2"
orbtk-css-engine = "0.3.0-alpha1"
orbtk-render = "0.3.0-alpha1"
orbtk-shell = "0.3.0-alpha1"
orbtk-utils = "0.3.0-alpha1"
orbtk-tree = "0.3.0-alpha1"
orbtk-theme = "0.3.0-alpha1"

[features]
debug = []