[package]
name = "orbtk-api"
version = "0.3.1-alpha2"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "API crate that provides base api and elements for OrbTk like widgets basis."
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["ui", "api"]
edition = "2018"

[dependencies]
serde = "1.0.104"
serde_derive = "1.0.104"
ron = "0.5.1"
dirs = "2.0.2"
dces = { git = "https://gitlab.redox-os.org/redox-os/dces-rust.git", branch = "develop" }
orbtk-utils = { path = "../utils", version = "0.3.1-alpha2" }
orbtk-tree = { path = "../tree", version = "0.3.1-alpha2" }
orbtk-css-engine = { path = "../css-engine", version = "0.3.1-alpha2" }
orbtk-render = { path = "../render", version = "0.3.1-alpha2" }
orbtk-shell = { path = "../shell", version = "0.3.1-alpha2" }
orbtk-theme = { path = "../theme", version = "0.3.1-alpha2" }
derive_more = "0.99.2"

[target.'cfg(all(not(target_arch = "wasm32")))'.dependencies]
raw-window-handle = "0.3.3"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.20"

[features]
debug = []
