name: test

on:
  push:
    branches:
      - master
      - develop

jobs:
  test: 
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
      
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: cargo test --lib --all --verbose
      - name: Test example
        run: cargo build --example widgets --verbose
      
  build_redox:
    name: Test on Redox OS
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set nightly default
        run:  rustup default nightly
      - name: Update
        run: sudo apt update
      - name: Install fuse
        run: sudo apt install libfuse-dev
      - name: Install redoxer
        run: cargo +nightly install redoxer
      - name: Install redoxer toolchain
        run: redoxer install
      - name: Test
        run: redoxer test --lib --all
           
  build_macos:
    name: Test on macOS-latest
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install rust
        run: brew install rust
      - name: Test
        run: cargo test --lib --all --verbose
